from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional


class PlanStep(BaseModel):
    """A single step in the execution plan."""
    agent: str = Field(
        ...,
        description="The agent responsible for this step. Must be 'collector', 'analyst', or 'communicator'.",
        pattern="^(collector|analyst|communicator)$"
    )
    task: str = Field(
        ...,
        description="A clear, actionable description of what the agent should do.",
        min_length=3
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional parameters needed for the task."
    )


class ExecutionPlan(BaseModel):
    """The complete execution plan generated by the planner."""
    execution_plan: List[PlanStep] = Field(
        ...,
        description="List of steps to execute, in order."
    )